name: WordPress DevOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate project files
        run: |
          test -f docker-compose.yml
          test -f docker/upload.ini
          test -f .gitignore

      - name: Validate Docker Compose
        run: docker compose config

      - name: Build Docker image
        run: docker build -t ghcr.io/abhinavjain132-sudo/wordpress-devops-project:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/abhinavjain132-sudo/wordpress-devops-project:latest